-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2026 NextTang contributors
-- Generated by scripts/build_diagnostic_boot.py from boot.asm.
-- Source SHA-256: d52437b6243d6dafd5eda9c8022bb62f7317fa3be82ab2017e4c5137f944736b

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity bootrom is
    port (
        CLK  : in  std_logic;
        ADDR : in  std_logic_vector(12 downto 0);
        DATA : out std_logic_vector(7 downto 0)
    );
end entity;

architecture rtl of bootrom is
    type rom_array is array (0 to 8191) of std_logic_vector(7 downto 0);
    constant rom : rom_array := (
        0 => x"f3",
        1 => x"31",
        4 => x"af",
        5 => x"d3",
        6 => x"fe",
        7 => x"21",
        8 => x"00",
        9 => x"40",
        10 => x"01",
        11 => x"00",
        12 => x"18",
        13 => x"16",
        14 => x"aa",
        15 => x"7a",
        16 => x"77",
        17 => x"2f",
        18 => x"57",
        19 => x"23",
        20 => x"0b",
        21 => x"78",
        22 => x"b1",
        23 => x"20",
        24 => x"f6",
        25 => x"21",
        26 => x"00",
        27 => x"58",
        28 => x"01",
        29 => x"00",
        30 => x"03",
        31 => x"16",
        32 => x"47",
        33 => x"7a",
        34 => x"77",
        35 => x"14",
        36 => x"23",
        37 => x"0b",
        38 => x"78",
        39 => x"b1",
        40 => x"20",
        41 => x"f7",
        42 => x"21",
        43 => x"00",
        44 => x"80",
        45 => x"01",
        46 => x"00",
        47 => x"40",
        48 => x"16",
        49 => x"5a",
        50 => x"7a",
        51 => x"77",
        52 => x"2f",
        53 => x"57",
        54 => x"23",
        55 => x"0b",
        56 => x"78",
        57 => x"b1",
        58 => x"20",
        59 => x"f6",
        60 => x"21",
        61 => x"00",
        62 => x"80",
        63 => x"01",
        64 => x"00",
        65 => x"40",
        66 => x"16",
        67 => x"5a",
        68 => x"7e",
        69 => x"ba",
        70 => x"20",
        71 => x"0f",
        72 => x"7a",
        73 => x"2f",
        74 => x"57",
        75 => x"23",
        76 => x"0b",
        77 => x"78",
        78 => x"b1",
        79 => x"20",
        80 => x"f3",
        81 => x"3e",
        82 => x"04",
        83 => x"d3",
        84 => x"fe",
        85 => x"18",
        86 => x"fe",
        87 => x"3e",
        88 => x"02",
        89 => x"d3",
        90 => x"fe",
        91 => x"18",
        92 => x"fa",
        8160 => x"4e",
        8161 => x"45",
        8162 => x"58",
        8163 => x"54",
        8164 => x"54",
        8165 => x"41",
        8166 => x"4e",
        8167 => x"47",
        8168 => x"20",
        8169 => x"44",
        8170 => x"49",
        8171 => x"41",
        8172 => x"47",
        8173 => x"20",
        8174 => x"31",
        8175 => x"00",
        others => x"ff"
    );
begin
    process (CLK)
    begin
        if rising_edge(CLK) then
            DATA <= rom(to_integer(unsigned(ADDR)));
        end if;
    end process;
end architecture;
