#!/usr/bin/env python3
"""Assemble the open diagnostic and render the core-compatible VHDL ROM."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile


ROM_SIZE = 8192
ASSEMBLER_TIMEOUT_SECONDS = 30


def assemble(assembler: str, source: Path) -> bytes:
    with tempfile.TemporaryDirectory() as temporary_directory:
        binary_path = Path(temporary_directory) / "boot.bin"
        result = subprocess.run(
            [
                assembler,
                "--nologo",
                "--msg=err",
                "--cleanonerror",
                f"--raw={binary_path}",
                str(source),
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=ASSEMBLER_TIMEOUT_SECONDS,
        )
        if result.returncode:
            detail = (result.stdout + result.stderr).strip()
            raise RuntimeError(f"diagnostic assembly failed: {detail}")
        image = binary_path.read_bytes()

    if len(image) != ROM_SIZE:
        raise ValueError(
            f"diagnostic image is {len(image)} bytes; expected {ROM_SIZE}"
        )
    return image


def render_vhdl(image: bytes, source: Path) -> str:
    if len(image) != ROM_SIZE:
        raise ValueError(f"ROM input is {len(image)} bytes; expected {ROM_SIZE}")

    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    entries = [
        f'        {address} => x"{value:02x}",'
        for address, value in enumerate(image)
        if value != 0xFF
    ]
    body = "\n".join(entries)
    return f"""-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2026 NextTang contributors
-- Generated by scripts/build_diagnostic_boot.py from {source.name}.
-- Source SHA-256: {source_hash}

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity bootrom is
    port (
        CLK  : in  std_logic;
        ADDR : in  std_logic_vector(12 downto 0);
        DATA : out std_logic_vector(7 downto 0)
    );
end entity;

architecture rtl of bootrom is
    type rom_array is array (0 to {ROM_SIZE - 1}) of std_logic_vector(7 downto 0);
    constant rom : rom_array := (
{body}
        others => x"ff"
    );
begin
    process (CLK)
    begin
        if rising_edge(CLK) then
            DATA <= rom(to_integer(unsigned(ADDR)));
        end if;
    end process;
end architecture;
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assembler", default="sjasmplus")
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    image = assemble(args.assembler, args.source)
    output = render_vhdl(image, args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
